# Generated by Django 3.1.3 on 2020-11-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='category',
            field=models.CharField(choices=[('politik', 'Politik'), ('wirtschaft', 'Wirtschaft'), ('wissenschaft', 'Wissenschaft'), ('kultur', 'Kultur'), ('beauty', 'Beauty'), ('sport', 'Sport'), ('sonstiges', 'Sonstiges')], default='other', max_length=255),
        ),
    ]
