# Generated by Django 3.1.3 on 2020-11-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tweet_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='is_fitting',
            field=models.BooleanField(max_length=255),
        ),
    ]
