# Generated by Django 3.1.3 on 2020-11-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
